services:
  - type: web
    name: freefire-telegram-bot
    env: node
    plan: free
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: BOT_TOKEN
        scope: build
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
